# Base image
FROM liquibase/liquibase:latest AS base

# Stage 1 - Add the MySQL and SQL Server JDBC drivers
FROM base AS jdbc-drivers
RUN curl -L -o /liquibase/lib/mysql-connector-j-9.0.0.jar \
    https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/9.0.0/mysql-connector-j-9.0.0.jar && \
    curl -L -o /liquibase/lib/mssql-jdbc-11.2.1.jre8.jar \
    https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/11.2.1.jre8/mssql-jdbc-11.2.1.jre8.jar

# Stage 2 - Install required packages and configure AWS CLI and Git
FROM jdbc-drivers AS final
USER root

# Update package manager and install required packages (unzip, curl, AWS CLI, git)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        unzip \
        curl \
        python3 \
        python3-pip \
        git && \
    pip3 install --no-cache-dir awscli && \
    apt-get remove --purge -y python3-pip && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*  # Clean up the apt cache

# Set the classpath for the JDBC drivers
ENV CLASSPATH=/liquibase/lib/mysql-connector-j-9.0.0.jar:/liquibase/lib/mssql-jdbc-11.2.1.jre8.jar

# Default command (can be overridden in Jenkins pipeline)
CMD ["liquibase", "--version"]
